version: "3"

# networks:
#   notifications:
#     name: notifications
#     external: true

services:
  server:
    image: containrrr/watchtower
    command: --interval 30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # networks:
    #   - notifications
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
    #   WATCHTOWER_NOTIFICATIONS: gotify
    #   WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN:
    #   WATCHTOWER_NOTIFICATION_GOTIFY_URL: http://gotify/
    #   WATCHTOWER_NOTIFICATION_GOTIFY_TLS_SKIP_VERIFY: true
